__lib_path := $(PROJECT_ROOT)/lib
__lib_files_list := queue.c
__lib_include_path := .
CPPFLAGS += $(addprefix -I$(__lib_path)/,$(__lib_include_path))
SOURCE_FILES_LIST += $(addprefix $(__lib_path)/, $(__lib_files_list))
