__lib_path := $(PROJECT_ROOT)/lib
__lib_files_list := array_queue/array_queue.c
__lib_include_path := array_queue
CPPFLAGS += $(addprefix -I$(__lib_path)/,$(__lib_include_path))
SOURCE_FILES_LIST += $(addprefix $(__lib_path)/, $(__lib_files_list))
